[package]
name = "ban-agent"
version = "0.1.0"
description = "Ban Agent: privileged control daemon of Ban OS"
edition.workspace = true
authors.workspace = true
publish.workspace = true
license-file.workspace = true

[dependencies]
ban-api-types = { path = "../../crates/ban-api-types" }

[package.metadata.deb]
revision = ""
assets = [["target/release/ban-agent", "opt/ban/agent/", "755"]]
